package script

const scriptTemplateLinux = `#!/bin/bash
# This script was generated by the application manager
# Do not edit this file manually

# This script will run the following services:
# {{if .ScriptName}}{{.ScriptName}}{{end}} {{if .ServiceName}}{{.ServiceName}}{{end}}

`

const scriptTemplateWindows = `@echo off
REM This script was generated by the application manager
REM Do not edit this file manually

REM This script will run the following services:
REM {{if .ScriptName}}{{.ScriptName}}{{end}} {{if .ServiceName}}{{.ServiceName}}{{end}}

`

const scriptTemplateService = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`

const scriptTemplateConfig = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`

const scriptTemplateEnd = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`

const scriptTemplateStop = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`

const scriptTemplateRun = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`

const scriptTemplateLoad = `{{if .ServiceName}}
# {{.ServiceName}}
{{end}}`
